### ISSUE TITLE
Trying to run on GPU

### ISSUE THREAD

**Issue by mhashas** [mlberkeley/oreilly-captions#11]
![image](https://cloud.githubusercontent.com/assets/13119609/26299536/6f50cf0e-3edb-11e7-8e23-341fc3e20581.png)

This is the error that I get when I try to build the gpu-based docker. I am unsure what I am doing wrong. I appreciate any advice/help. Thank you :)

**Comment by raulpuric** [comment]
Fixed in the latest commit
