### ISSUE TITLE
get_data() in O'Reilly Training.ipynb make kernel issues

### ISSUE THREAD

**Issue by ccqpein** [mlberkeley/oreilly-captions#12]
I use docker to run `Caption this, with TensorFlow`. I followed everything in readme and when I run `feats, captions = get_data(annotation_path, feature_path)` Jupyter show alart that "The kernel appears to have died. It will restart automatically" everytime.

Do I miss something? How could I fix this issue?

Thank you!

**Comment by raulpuric** [comment]
Ahh my apologies.
When I was trying to train, a set of preloaded weights I removed the memory mapping from the call to `np.load(...)` to speed up IO. The docker container (and some laptops too) does not have enough memory to load the features which sits at ~5.9 GB. I've added back the memory map in the most recent commit.
