### ISSUE TITLE
KeyError: "The name 'import/Relu_1:0' refers to a Tensor which does not exist. The operation, 'import/Relu_1', does not exist in the graph."

### ISSUE THREAD

**Issue by jodekirk** [mlberkeley/oreilly-captions#2]
Using Docker with Windows 10. All steps run in jupyter notebook except the last command on 3. O'Reilly Generate from image.ipynb

test(sess,image,generated_words,ixtoword, image_path)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-10-31dc7c363274> in <module>()
----> 1 test(sess,image,generated_words,ixtoword, image_path)

<ipython-input-9-24edd5028301> in test(sess, image, generated_words, ixtoword, test_image_path)
      4 
      5     feat = read_image(test_image_path)
----> 6     fc7 = sess.run(graph.get_tensor_by_name("import/Relu_1:0"), feed_dict={images:feat})
      7 
      8     saver = tf.train.Saver()

/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py in get_tensor_by_name(self, name)
   2620       raise TypeError("Tensor names are strings (or similar), not %s."
   2621                       % type(name).__name__)
-> 2622     return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
   2623 
   2624   def _next_id(self):

/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py in as_graph_element(self, obj, allow_tensor, allow_operation)
   2471 
   2472     with self._lock:
-> 2473       return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
   2474 
   2475   def _as_graph_element_locked(self, obj, allow_tensor, allow_operation):

/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py in _as_graph_element_locked(self, obj, allow_tensor, allow_operation)
   2513           raise KeyError("The name %s refers to a Tensor which does not "
   2514                          "exist. The operation, %s, does not exist in the "
-> 2515                          "graph." % (repr(name), repr(op_name)))
   2516         try:
   2517           return op.outputs[out_n]

KeyError: "The name 'import/Relu_1:0' refers to a Tensor which does not exist. The operation, 'import/Relu_1', does not exist in the graph."

**Comment by raulpuric** [comment]
That line is attempting to pull the feature embedding from one of the last layers of the VGG-16 network. The error it's getting is due to one of two reasons: 
The graph did not get properly loaded in one of the previous cells, which could have been because the cell wasn't run, or the graph checkpoint (the lstm/non-vgg16 portion) wasn't properly saved from the prior notebooks.

It could also be that the version of the vgg16 model graph (what was the file name when you downloaded the model from google drive) you downloaded is somehow different from the one we had hosted when we wrote this notebook, and has had it's last relu layer from the 7th fully connected portion of vgg-16 renamed. To figure out what it's been renamed to utilize the following command to list the names of all tensors in the graph. Swap the name as appropriate.
    ```
    [n.name for n in tf.get_default_graph().as_graph_def().node]
    ```
You can also utilize alex's nice graph visualization tool from his deep dream notebook to render the graph and figure out the names of the graph nodes.

**Comment by Feynman27** [comment]
When loading VGG16 using ```tf.import_graph_def```, the graph is loaded onto the current default graph (see [doc](https://www.tensorflow.org/versions/r1.1/api_docs/python/tf/import_graph_def)).

So, when loading the graph from VGG16, change the line
```python 
graph = tf.Graph()
sess = tf.InteractiveSession(graph=graph)
```
to
```python
graph = tf.get_default_graph()
sess = tf.InteractiveSession(graph=graph)
```

**Comment by jodekirk** [comment]
I ran the first command: tensor.name for tensor in tf.get_default_graph().as_graph_def().node
But I have no idea which name to use instead to fix this line:
fc7 = sess.run(graph.get_tensor_by_name("import/Relu_1:0"), feed_dict={images:feat})

tensor.name for tensor in tf.get_default_graph().as_graph_def().node
Gives these results:

['random_uniform/shape',
 'random_uniform/min',
 'random_uniform/max',
 'random_uniform/RandomUniform',
 'random_uniform/sub',
 'random_uniform/mul',
 'random_uniform',
 'word_embedding',
 'word_embedding/Assign',
 'word_embedding/read',
 'zeros',
 'embedding_bias',
 'embedding_bias/Assign',
 'embedding_bias/read',
 'random_uniform_1/shape',
 'random_uniform_1/min',
 'random_uniform_1/max',
 'random_uniform_1/RandomUniform',
 'random_uniform_1/sub',
 'random_uniform_1/mul',
 'random_uniform_1',
 'img_embedding',
 'img_embedding/Assign',
 'img_embedding/read',
 'zeros_1',
 'img_embedding_bias',
 'img_embedding_bias/Assign',
 'img_embedding_bias/read',
 'random_uniform_2/shape',
 'random_uniform_2/min',
 'random_uniform_2/max',
 'random_uniform_2/RandomUniform',
 'random_uniform_2/sub',
 'random_uniform_2/mul',
 'random_uniform_2',
 'word_encoding',
 'word_encoding/Assign',
 'word_encoding/read',
 'zeros_2',
 'word_encoding_bias',
 'word_encoding_bias/Assign',
 'word_encoding_bias/read',
 'Placeholder',
 'MatMul',
 'add',
 'stack',
 'zeros_3/Const',
 'zeros_3',
 'stack_1',
 'zeros_4/Const',
 'zeros_4',
 'RNN/basic_lstm_cell/weights/Initializer/random_uniform/shape',
 'RNN/basic_lstm_cell/weights/Initializer/random_uniform/min',
 'RNN/basic_lstm_cell/weights/Initializer/random_uniform/max',
 'RNN/basic_lstm_cell/weights/Initializer/random_uniform/RandomUniform',
 'RNN/basic_lstm_cell/weights/Initializer/random_uniform/sub',
 'RNN/basic_lstm_cell/weights/Initializer/random_uniform/mul',
 'RNN/basic_lstm_cell/weights/Initializer/random_uniform',
 'RNN/basic_lstm_cell/weights',
 'RNN/basic_lstm_cell/weights/Assign',
 'RNN/basic_lstm_cell/weights/read',
 'RNN/basic_lstm_cell/basic_lstm_cell/concat/axis',
 'RNN/basic_lstm_cell/basic_lstm_cell/concat',
 'RNN/basic_lstm_cell/basic_lstm_cell/MatMul',
 'RNN/basic_lstm_cell/biases/Initializer/Const',
 'RNN/basic_lstm_cell/biases',
 'RNN/basic_lstm_cell/biases/Assign',
 'RNN/basic_lstm_cell/biases/read',
 'RNN/basic_lstm_cell/BiasAdd',
 'RNN/basic_lstm_cell/split/split_dim',
 'RNN/basic_lstm_cell/split',
 'RNN/basic_lstm_cell/add/y',
 'RNN/basic_lstm_cell/add',
 'RNN/basic_lstm_cell/Sigmoid',
 'RNN/basic_lstm_cell/mul',
 'RNN/basic_lstm_cell/Sigmoid_1',
 'RNN/basic_lstm_cell/Tanh',
 'RNN/basic_lstm_cell/mul_1',
 'RNN/basic_lstm_cell/add_1',
 'RNN/basic_lstm_cell/Tanh_1',
 'RNN/basic_lstm_cell/Sigmoid_2',
 'RNN/basic_lstm_cell/mul_2',
 'RNN/embedding_lookup/indices',
 'RNN/embedding_lookup',
 'RNN/add',
 'RNN/basic_lstm_cell_1/basic_lstm_cell/concat/axis',
 'RNN/basic_lstm_cell_1/basic_lstm_cell/concat',
 'RNN/basic_lstm_cell_1/basic_lstm_cell/MatMul',
 'RNN/basic_lstm_cell_1/BiasAdd',
 'RNN/basic_lstm_cell_1/split/split_dim',
 'RNN/basic_lstm_cell_1/split',
 'RNN/basic_lstm_cell_1/add/y',
 'RNN/basic_lstm_cell_1/add',
 'RNN/basic_lstm_cell_1/Sigmoid',
 'RNN/basic_lstm_cell_1/mul',
 'RNN/basic_lstm_cell_1/Sigmoid_1',
 'RNN/basic_lstm_cell_1/Tanh',
 'RNN/basic_lstm_cell_1/mul_1',
 'RNN/basic_lstm_cell_1/add_1',
 'RNN/basic_lstm_cell_1/Tanh_1',
 'RNN/basic_lstm_cell_1/Sigmoid_2',
 'RNN/basic_lstm_cell_1/mul_2',
 'RNN/MatMul',
 'RNN/add_1',
 'RNN/ArgMax/dimension',
 'RNN/ArgMax',
 'RNN/embedding_lookup_1',
 'RNN/add_2',
 'RNN/basic_lstm_cell_2/basic_lstm_cell/concat/axis',
 'RNN/basic_lstm_cell_2/basic_lstm_cell/concat',
 'RNN/basic_lstm_cell_2/basic_lstm_cell/MatMul',
 'RNN/basic_lstm_cell_2/BiasAdd',
 'RNN/basic_lstm_cell_2/split/split_dim',
 'RNN/basic_lstm_cell_2/split',
 'RNN/basic_lstm_cell_2/add/y',
 'RNN/basic_lstm_cell_2/add',
 'RNN/basic_lstm_cell_2/Sigmoid',
 'RNN/basic_lstm_cell_2/mul',
 'RNN/basic_lstm_cell_2/Sigmoid_1',
 'RNN/basic_lstm_cell_2/Tanh',
 'RNN/basic_lstm_cell_2/mul_1',
 'RNN/basic_lstm_cell_2/add_1',
 'RNN/basic_lstm_cell_2/Tanh_1',
 'RNN/basic_lstm_cell_2/Sigmoid_2',
 'RNN/basic_lstm_cell_2/mul_2',
 'RNN/MatMul_1',
 'RNN/add_3',
 'RNN/ArgMax_1/dimension',
 'RNN/ArgMax_1',
 'RNN/embedding_lookup_2',
 'RNN/add_4',
 'RNN/basic_lstm_cell_3/basic_lstm_cell/concat/axis',
 'RNN/basic_lstm_cell_3/basic_lstm_cell/concat',
 'RNN/basic_lstm_cell_3/basic_lstm_cell/MatMul',
 'RNN/basic_lstm_cell_3/BiasAdd',
 'RNN/basic_lstm_cell_3/split/split_dim',
 'RNN/basic_lstm_cell_3/split',
 'RNN/basic_lstm_cell_3/add/y',
 'RNN/basic_lstm_cell_3/add',
 'RNN/basic_lstm_cell_3/Sigmoid',
 'RNN/basic_lstm_cell_3/mul',
 'RNN/basic_lstm_cell_3/Sigmoid_1',
 'RNN/basic_lstm_cell_3/Tanh',
 'RNN/basic_lstm_cell_3/mul_1',
 'RNN/basic_lstm_cell_3/add_1',
 'RNN/basic_lstm_cell_3/Tanh_1',
 'RNN/basic_lstm_cell_3/Sigmoid_2',
 'RNN/basic_lstm_cell_3/mul_2',
 'RNN/MatMul_2',
 'RNN/add_5',
 'RNN/ArgMax_2/dimension',
 'RNN/ArgMax_2',
 'RNN/embedding_lookup_3',
 'RNN/add_6',
 'RNN/basic_lstm_cell_4/basic_lstm_cell/concat/axis',
 'RNN/basic_lstm_cell_4/basic_lstm_cell/concat',
 'RNN/basic_lstm_cell_4/basic_lstm_cell/MatMul',
 'RNN/basic_lstm_cell_4/BiasAdd',
 'RNN/basic_lstm_cell_4/split/split_dim',
 'RNN/basic_lstm_cell_4/split',
 'RNN/basic_lstm_cell_4/add/y',
 'RNN/basic_lstm_cell_4/add',
 'RNN/basic_lstm_cell_4/Sigmoid',
 'RNN/basic_lstm_cell_4/mul',
 'RNN/basic_lstm_cell_4/Sigmoid_1',
 'RNN/basic_lstm_cell_4/Tanh',
 'RNN/basic_lstm_cell_4/mul_1',
 'RNN/basic_lstm_cell_4/add_1',
 'RNN/basic_lstm_cell_4/Tanh_1',
 'RNN/basic_lstm_cell_4/Sigmoid_2',
 'RNN/basic_lstm_cell_4/mul_2',
 'RNN/MatMul_3',
 'RNN/add_7',
 'RNN/ArgMax_3/dimension',
 'RNN/ArgMax_3',
 'RNN/embedding_lookup_4',
 'RNN/add_8',
 'RNN/basic_lstm_cell_5/basic_lstm_cell/concat/axis',
 'RNN/basic_lstm_cell_5/basic_lstm_cell/concat',
 'RNN/basic_lstm_cell_5/basic_lstm_cell/MatMul',
 'RNN/basic_lstm_cell_5/BiasAdd',
 'RNN/basic_lstm_cell_5/split/split_dim',
 'RNN/basic_lstm_cell_5/split',
 'RNN/basic_lstm_cell_5/add/y',
 'RNN/basic_lstm_cell_5/add',
 'RNN/basic_lstm_cell_5/Sigmoid',
 'RNN/basic_lstm_cell_5/mul',
 'RNN/basic_lstm_cell_5/Sigmoid_1',
 'RNN/basic_lstm_cell_5/Tanh',
 'RNN/basic_lstm_cell_5/mul_1',
 'RNN/basic_lstm_cell_5/add_1',
 'RNN/basic_lstm_cell_5/Tanh_1',
 'RNN/basic_lstm_cell_5/Sigmoid_2',
 'RNN/basic_lstm_cell_5/mul_2',
 'RNN/MatMul_4',
 'RNN/add_9',
 'RNN/ArgMax_4/dimension',
 'RNN/ArgMax_4',
 'RNN/embedding_lookup_5',
 'RNN/add_10',
 'RNN/basic_lstm_cell_6/basic_lstm_cell/concat/axis',
 'RNN/basic_lstm_cell_6/basic_lstm_cell/concat',
 'RNN/basic_lstm_cell_6/basic_lstm_cell/MatMul',
 'RNN/basic_lstm_cell_6/BiasAdd',
 'RNN/basic_lstm_cell_6/split/split_dim',
 'RNN/basic_lstm_cell_6/split',
 'RNN/basic_lstm_cell_6/add/y',
 'RNN/basic_lstm_cell_6/add',
 'RNN/basic_lstm_cell_6/Sigmoid',
 'RNN/basic_lstm_cell_6/mul',
 'RNN/basic_lstm_cell_6/Sigmoid_1',
 'RNN/basic_lstm_cell_6/Tanh',
 'RNN/basic_lstm_cell_6/mul_1',
 'RNN/basic_lstm_cell_6/add_1',
 'RNN/basic_lstm_cell_6/Tanh_1',
 'RNN/basic_lstm_cell_6/Sigmoid_2',
 'RNN/basic_lstm_cell_6/mul_2',
 'RNN/MatMul_5',
 'RNN/add_11',
 'RNN/ArgMax_5/dimension',
 'RNN/ArgMax_5',
 'RNN/embedding_lookup_6',
 'RNN/add_12',
 'RNN/basic_lstm_cell_7/basic_lstm_cell/concat/axis',
 'RNN/basic_lstm_cell_7/basic_lstm_cell/concat',
 'RNN/basic_lstm_cell_7/basic_lstm_cell/MatMul',
 'RNN/basic_lstm_cell_7/BiasAdd',
 'RNN/basic_lstm_cell_7/split/split_dim',
 'RNN/basic_lstm_cell_7/split',
 'RNN/basic_lstm_cell_7/add/y',
 'RNN/basic_lstm_cell_7/add',
 'RNN/basic_lstm_cell_7/Sigmoid',
 'RNN/basic_lstm_cell_7/mul',
 'RNN/basic_lstm_cell_7/Sigmoid_1',
 'RNN/basic_lstm_cell_7/Tanh',
 'RNN/basic_lstm_cell_7/mul_1',
 'RNN/basic_lstm_cell_7/add_1',
 'RNN/basic_lstm_cell_7/Tanh_1',
 'RNN/basic_lstm_cell_7/Sigmoid_2',
 'RNN/basic_lstm_cell_7/mul_2',
 'RNN/MatMul_6',
 'RNN/add_13',
 'RNN/ArgMax_6/dimension',
 'RNN/ArgMax_6',
 'RNN/embedding_lookup_7',
 'RNN/add_14',
 'RNN/basic_lstm_cell_8/basic_lstm_cell/concat/axis',
 'RNN/basic_lstm_cell_8/basic_lstm_cell/concat',
 'RNN/basic_lstm_cell_8/basic_lstm_cell/MatMul',
 'RNN/basic_lstm_cell_8/BiasAdd',
 'RNN/basic_lstm_cell_8/split/split_dim',
 'RNN/basic_lstm_cell_8/split',
 'RNN/basic_lstm_cell_8/add/y',
 'RNN/basic_lstm_cell_8/add',
 'RNN/basic_lstm_cell_8/Sigmoid',
 'RNN/basic_lstm_cell_8/mul',
 'RNN/basic_lstm_cell_8/Sigmoid_1',
 'RNN/basic_lstm_cell_8/Tanh',
 'RNN/basic_lstm_cell_8/mul_1',
 'RNN/basic_lstm_cell_8/add_1',
 'RNN/basic_lstm_cell_8/Tanh_1',
 'RNN/basic_lstm_cell_8/Sigmoid_2',
 'RNN/basic_lstm_cell_8/mul_2',
 'RNN/MatMul_7',
 'RNN/add_15',
 'RNN/ArgMax_7/dimension',
 'RNN/ArgMax_7',
 'RNN/embedding_lookup_8',
 'RNN/add_16',
 'RNN/basic_lstm_cell_9/basic_lstm_cell/concat/axis',
 'RNN/basic_lstm_cell_9/basic_lstm_cell/concat',
 'RNN/basic_lstm_cell_9/basic_lstm_cell/MatMul',
 'RNN/basic_lstm_cell_9/BiasAdd',
 'RNN/basic_lstm_cell_9/split/split_dim',
 'RNN/basic_lstm_cell_9/split',
 'RNN/basic_lstm_cell_9/add/y',
 'RNN/basic_lstm_cell_9/add',
 'RNN/basic_lstm_cell_9/Sigmoid',
 'RNN/basic_lstm_cell_9/mul',
 'RNN/basic_lstm_cell_9/Sigmoid_1',
 'RNN/basic_lstm_cell_9/Tanh',
 'RNN/basic_lstm_cell_9/mul_1',
 'RNN/basic_lstm_cell_9/add_1',
 'RNN/basic_lstm_cell_9/Tanh_1',
 'RNN/basic_lstm_cell_9/Sigmoid_2',
 'RNN/basic_lstm_cell_9/mul_2',
 'RNN/MatMul_8',
 'RNN/add_17',
 'RNN/ArgMax_8/dimension',
 'RNN/ArgMax_8',
 'RNN/embedding_lookup_9',
 'RNN/add_18',
 'RNN/basic_lstm_cell_10/basic_lstm_cell/concat/axis',
 'RNN/basic_lstm_cell_10/basic_lstm_cell/concat',
 'RNN/basic_lstm_cell_10/basic_lstm_cell/MatMul',
 'RNN/basic_lstm_cell_10/BiasAdd',
 'RNN/basic_lstm_cell_10/split/split_dim',
 'RNN/basic_lstm_cell_10/split',
 'RNN/basic_lstm_cell_10/add/y',
 'RNN/basic_lstm_cell_10/add',
 'RNN/basic_lstm_cell_10/Sigmoid',
 'RNN/basic_lstm_cell_10/mul',
 'RNN/basic_lstm_cell_10/Sigmoid_1',
 'RNN/basic_lstm_cell_10/Tanh',
 'RNN/basic_lstm_cell_10/mul_1',
 'RNN/basic_lstm_cell_10/add_1',
 'RNN/basic_lstm_cell_10/Tanh_1',
 'RNN/basic_lstm_cell_10/Sigmoid_2',
 'RNN/basic_lstm_cell_10/mul_2',
 'RNN/MatMul_9',
 'RNN/add_19',
 'RNN/ArgMax_9/dimension',
 'RNN/ArgMax_9',
 'RNN/embedding_lookup_10',
 'RNN/add_20',
 'RNN/basic_lstm_cell_11/basic_lstm_cell/concat/axis',
 'RNN/basic_lstm_cell_11/basic_lstm_cell/concat',
 'RNN/basic_lstm_cell_11/basic_lstm_cell/MatMul',
 'RNN/basic_lstm_cell_11/BiasAdd',
 'RNN/basic_lstm_cell_11/split/split_dim',
 'RNN/basic_lstm_cell_11/split',
 'RNN/basic_lstm_cell_11/add/y',
 'RNN/basic_lstm_cell_11/add',
 'RNN/basic_lstm_cell_11/Sigmoid',
 'RNN/basic_lstm_cell_11/mul',
 'RNN/basic_lstm_cell_11/Sigmoid_1',
 'RNN/basic_lstm_cell_11/Tanh',
 'RNN/basic_lstm_cell_11/mul_1',
 'RNN/basic_lstm_cell_11/add_1',
 'RNN/basic_lstm_cell_11/Tanh_1',
 'RNN/basic_lstm_cell_11/Sigmoid_2',
 'RNN/basic_lstm_cell_11/mul_2',
 'RNN/MatMul_10',
 'RNN/add_21',
 'RNN/ArgMax_10/dimension',
 'RNN/ArgMax_10',
 'RNN/embedding_lookup_11',
 'RNN/add_22',
 'RNN/basic_lstm_cell_12/basic_lstm_cell/concat/axis',
 'RNN/basic_lstm_cell_12/basic_lstm_cell/concat',
 'RNN/basic_lstm_cell_12/basic_lstm_cell/MatMul',
 'RNN/basic_lstm_cell_12/BiasAdd',
 'RNN/basic_lstm_cell_12/split/split_dim',
 'RNN/basic_lstm_cell_12/split',
 'RNN/basic_lstm_cell_12/add/y',
 'RNN/basic_lstm_cell_12/add',
 'RNN/basic_lstm_cell_12/Sigmoid',
 'RNN/basic_lstm_cell_12/mul',
 'RNN/basic_lstm_cell_12/Sigmoid_1',
 'RNN/basic_lstm_cell_12/Tanh',
 'RNN/basic_lstm_cell_12/mul_1',
 'RNN/basic_lstm_cell_12/add_1',
 'RNN/basic_lstm_cell_12/Tanh_1',
 'RNN/basic_lstm_cell_12/Sigmoid_2',
 'RNN/basic_lstm_cell_12/mul_2',
 'RNN/MatMul_11',
 'RNN/add_23',
 'RNN/ArgMax_11/dimension',
 'RNN/ArgMax_11',
 'RNN/embedding_lookup_12',
 'RNN/add_24',
 'RNN/basic_lstm_cell_13/basic_lstm_cell/concat/axis',
 'RNN/basic_lstm_cell_13/basic_lstm_cell/concat',
 'RNN/basic_lstm_cell_13/basic_lstm_cell/MatMul',
 'RNN/basic_lstm_cell_13/BiasAdd',
 'RNN/basic_lstm_cell_13/split/split_dim',
 'RNN/basic_lstm_cell_13/split',
 'RNN/basic_lstm_cell_13/add/y',
 'RNN/basic_lstm_cell_13/add',
 'RNN/basic_lstm_cell_13/Sigmoid',
 'RNN/basic_lstm_cell_13/mul',
 'RNN/basic_lstm_cell_13/Sigmoid_1',
 'RNN/basic_lstm_cell_13/Tanh',
 'RNN/basic_lstm_cell_13/mul_1',
 'RNN/basic_lstm_cell_13/add_1',
 'RNN/basic_lstm_cell_13/Tanh_1',
 'RNN/basic_lstm_cell_13/Sigmoid_2',
 'RNN/basic_lstm_cell_13/mul_2',
 'RNN/MatMul_12',
 'RNN/add_25',
 'RNN/ArgMax_12/dimension',
 'RNN/ArgMax_12',
 'RNN/embedding_lookup_13',
 'RNN/add_26',
 'RNN/basic_lstm_cell_14/basic_lstm_cell/concat/axis',
 'RNN/basic_lstm_cell_14/basic_lstm_cell/concat',
 'RNN/basic_lstm_cell_14/basic_lstm_cell/MatMul',
 'RNN/basic_lstm_cell_14/BiasAdd',
 'RNN/basic_lstm_cell_14/split/split_dim',
 'RNN/basic_lstm_cell_14/split',
 'RNN/basic_lstm_cell_14/add/y',
 'RNN/basic_lstm_cell_14/add',
 'RNN/basic_lstm_cell_14/Sigmoid',
 'RNN/basic_lstm_cell_14/mul',
 'RNN/basic_lstm_cell_14/Sigmoid_1',
 'RNN/basic_lstm_cell_14/Tanh',
 'RNN/basic_lstm_cell_14/mul_1',
 'RNN/basic_lstm_cell_14/add_1',
 'RNN/basic_lstm_cell_14/Tanh_1',
 'RNN/basic_lstm_cell_14/Sigmoid_2',
 'RNN/basic_lstm_cell_14/mul_2',
 'RNN/MatMul_13',
 'RNN/add_27',
 'RNN/ArgMax_13/dimension',
 'RNN/ArgMax_13',
 'RNN/embedding_lookup_14',
 'RNN/add_28',
 'RNN/basic_lstm_cell_15/basic_lstm_cell/concat/axis',
 'RNN/basic_lstm_cell_15/basic_lstm_cell/concat',
 'RNN/basic_lstm_cell_15/basic_lstm_cell/MatMul',
 'RNN/basic_lstm_cell_15/BiasAdd',
 'RNN/basic_lstm_cell_15/split/split_dim',
 'RNN/basic_lstm_cell_15/split',
 'RNN/basic_lstm_cell_15/add/y',
 'RNN/basic_lstm_cell_15/add',
 'RNN/basic_lstm_cell_15/Sigmoid',
 'RNN/basic_lstm_cell_15/mul',
 'RNN/basic_lstm_cell_15/Sigmoid_1',
 'RNN/basic_lstm_cell_15/Tanh',
 'RNN/basic_lstm_cell_15/mul_1',
 'RNN/basic_lstm_cell_15/add_1',
 'RNN/basic_lstm_cell_15/Tanh_1',
 'RNN/basic_lstm_cell_15/Sigmoid_2',
 'RNN/basic_lstm_cell_15/mul_2',
 'RNN/MatMul_14',
 'RNN/add_29',
 'RNN/ArgMax_14/dimension',
 'RNN/ArgMax_14',
 'RNN/embedding_lookup_15',
 'RNN/add_30']

**Comment by raulpuric** [comment]
Hi it's like @Feynman27 said. It seems like this change slipped through on a Git Merge.

We're fixing it and closing this issue when complete.
