### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'astype'

### ISSUE THREAD

**Issue by jodekirk** [mlberkeley/oreilly-captions#3]
I tried the new 3. O'Reilly Generate from image and there is a new error on the last line:
test(sess,image,generated_words,ixtoword, image_path)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-31dc7c363274> in <module>()
----> 1 test(sess,image,generated_words,ixtoword, image_path)

<ipython-input-9-24edd5028301> in test(sess, image, generated_words, ixtoword, test_image_path)
      3 
      4 
----> 5     feat = read_image(test_image_path)
      6     fc7 = sess.run(graph.get_tensor_by_name("import/Relu_1:0"), feed_dict={images:feat})
      7 

<ipython-input-8-c801f41e0027> in read_image(path)
      1 def read_image(path):
      2 
----> 3      img = crop_image(path, target_height=224, target_width=224)
      4      if img.shape[2] == 4:
      5          img = img[:,:,:3]

<ipython-input-7-1cd92c88b424> in crop_image(x, target_height, target_width, as_float)
      2     image = cv2.imread(x)
      3     if as_float:
----> 4         image = image.astype(np.float32)
      5 
      6     if len(image.shape) == 2:

AttributeError: 'NoneType' object has no attribute 'astype'

**Comment by raulpuric** [comment]
Hi,
What's your image path. Opencv is most likely returning None because it hasn't found your image. This goes on to cause the Nonetype error.

**Comment by raulpuric** [comment]
Is this closed @jodekirk

**Comment by jodekirk** [comment]
Thanks. After replacing my copy of the file, I forgot to update the image path.
