### ISSUE TITLE
Running 3. on two images in a row is disallowed

### ISSUE THREAD

**Issue by jodekirk** [mlberkeley/oreilly-captions#5]
Have to restart Kernel each time 3. is run or the following error generates:

ValueError: Variable RNN/basic_lstm_cell/weights already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell_impl.py", line 747, in _linear
    "weights", [total_arg_size, output_size], dtype=dtype)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell_impl.py", line 179, in __call__
    concat = _linear([inputs, h], 4 * self._num_units, True, scope=scope)
  File "<ipython-input-5-7c0cc7cce63d>", line 97, in build_generator
    output, state = self.lstm(image_embedding, state)

**Comment by raulpuric** [comment]
Hi,
This again has to do with graph definitions.
You actually have to rerun the 
```
if not os.path.exists('data/ixtoword.npy'):
    print ('You must run 1. O\'reilly Training.ipynb first.')
else:    
    with open(vgg_path,'rb') as f:
        fileContent = f.read()
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(fileContent)
        ...
```
cell.
We'll restructure the notebook to make this explicit.

**Comment by pcuenca** [comment]
@jodekirk or run `tf.reset_default_graph()` and then run the notebook again.

Or simply create and run additional cells that just invoke the `test` function any number of times; no need to execute all the previous steps every time:
```python
image_path = '/data/pictures/2016/2016-04-26/DSCF2776.JPG'
test(sess,image,generated_words,ixtoword, image_path)
image_path = '/data/pictures/2016/2016-04-26/DSCF2789.JPG'
test(sess,image,generated_words,ixtoword, image_path)
```

**Comment by raulpuric** [comment]
added calls to `tf.reset_default_graph()` in one of the latests [commits](https://github.com/mlberkeley/oreilly-captions/commit/942e81165cb350060c0fa004d1bb7f6d999336f9):
