### ISSUE TITLE
Pretrained weights for oreilly-captions model?

### ISSUE THREAD

**Issue by prerna135** [mlberkeley/oreilly-captions#7]
Can someone release a pre-trained model for the oreilly-captions model trained on Flickr30k? Would be great for someone here who doesn't have the computational resource yet to do a full training run. Thanks!

**Comment by raulpuric** [comment]
There's already a trained CNN. You can train a very reasonable caption generator from this in ~24 hours on CPU. We'll be releasing a pretrained model and some updates on the 30th.

**Comment by raulpuric** [comment]
Hi, sorry for the wait. We've added checkpoint files trained to 500 epochs. :)
