### ISSUE TITLE
Do we have to use docker?

### ISSUE THREAD

**Issue by Yiyiii** [mlberkeley/oreilly-captions#8]
I have problems to use docker toolbox on windows which i can not sovle by network resource.
Acturlly, i have confused for several days, so is docker just a  recommendation? 
Thanks.

**Comment by philkuz** [comment]
You do not need docker, but you would need to install all the software that the docker file installs.

**Comment by Yiyiii** [comment]
i change to use win10, docker can be used. But  i find a problem, most softs depend on Ubuntu in dockerfile. mainly i am not familiar with docker, so i still don't understand the function of the docker in this project, the pull(mlatberkeley/showandtell) is a file(oreilly-captions) , right? 
i try directly run the code in .ipynb by using Anaconda( however there are new problems), now i find some video to learn docker.[i install Anaconda to build tensorflow and opencv2 which still use ipython nootbook]
hope i can make it as quickly as possible.
Thanks again.
